const fs = require('fs');
const path = require('path');

const rawData = [
  { prov: "Aceh", nama: "Kabupaten Aceh Barat" },
  { prov: "Aceh", nama: "Kabupaten Aceh Besar" },
  { prov: "Aceh", nama: "Kabupaten Aceh Jaya" },
  { prov: "Aceh", nama: "Kabupaten Aceh Selatan" },
  { prov: "Aceh", nama: "Kabupaten Aceh Singkil" },
  { prov: "Aceh", nama: "Kabupaten Aceh Tamiang" },
  { prov: "Aceh", nama: "Kabupaten Aceh Tengah" },
  { prov: "Aceh", nama: "Kabupaten Aceh Tenggara" },
  { prov: "Aceh", nama: "Kabupaten Aceh Timur" },
  { prov: "Aceh", nama: "Kabupaten Aceh Utara" },
  { prov: "Aceh", nama: "Kabupaten Bener Meriah" },
  { prov: "Aceh", nama: "Kabupaten Bireuen" },
  { prov: "Aceh", nama: "Kabupaten Gayo Lues" },
  { prov: "Aceh", nama: "Kabupaten Nagan Raya" },
  { prov: "Aceh", nama: "Kabupaten Pidie" },
  { prov: "Aceh", nama: "Kabupaten Pidie Jaya" },
  { prov: "Aceh", nama: "Kota Banda Aceh" },
  { prov: "Aceh", nama: "Kota Langsa" },
  { prov: "Aceh", nama: "Kota Lhokseumawe" },
  { prov: "Aceh", nama: "Kota Sabang" },
  { prov: "Aceh", nama: "Kota Subulussalam" },

  { prov: "Sumatera Utara", nama: "Kabupaten Asahan" },
  { prov: "Sumatera Utara", nama: "Kabupaten Batubara" },
  { prov: "Sumatera Utara", nama: "Kabupaten Dairi" },
  { prov: "Sumatera Utara", nama: "Kabupaten Deli Serdang" },
  { prov: "Sumatera Utara", nama: "Kabupaten Humbang Hasundutan" },
  { prov: "Sumatera Utara", nama: "Kabupaten Karo" },
  { prov: "Sumatera Utara", nama: "Kabupaten Labuhanbatu" },
  { prov: "Sumatera Utara", nama: "Kabupaten Labuhanbatu Selatan" },
  { prov: "Sumatera Utara", nama: "Kabupaten Labuhanbatu Utara" },
  { prov: "Sumatera Utara", nama: "Kabupaten Langkat" },
  { prov: "Sumatera Utara", nama: "Kabupaten Mandailing Natal" },
  { prov: "Sumatera Utara", nama: "Kabupaten Nias" },
  { prov: "Sumatera Utara", nama: "Kabupaten Padang Lawas" },
  { prov: "Sumatera Utara", nama: "Kabupaten Pakpak Bharat" },
  { prov: "Sumatera Utara", nama: "Kabupaten Samosir" },
  { prov: "Sumatera Utara", nama: "Kabupaten Serdang Bedagai" },
  { prov: "Sumatera Utara", nama: "Kabupaten Simalungun" },
  { prov: "Sumatera Utara", nama: "Kabupaten Tapanuli Selatan" },
  { prov: "Sumatera Utara", nama: "Kabupaten Tapanuli Tengah" },
  { prov: "Sumatera Utara", nama: "Kabupaten Tapanuli Utara" },
  { prov: "Sumatera Utara", nama: "Kabupaten Toba" },
  { prov: "Sumatera Utara", nama: "Kota Binjai" },
  { prov: "Sumatera Utara", nama: "Kota Medan" },
  { prov: "Sumatera Utara", nama: "Kota Padangsidimpuan" },
  { prov: "Sumatera Utara", nama: "Kota Pematangsiantar" },
  { prov: "Sumatera Utara", nama: "Kota Sibolga" },
  { prov: "Sumatera Utara", nama: "Kota Tanjungbalai" },
  { prov: "Sumatera Utara", nama: "Kota Tebing Tinggi" },
  { prov: "Sumatera Utara", nama: "Kota Kisaran" },
  { prov: "Sumatera Utara", nama: "Kota Rantau Prapat" },
  { prov: "Sumatera Utara", nama: "Sei Semangkei" },
  { prov: "Sumatera Utara", nama: "Kota Stabat" },
  { prov: "Sumatera Utara", nama: "Kota Pangkalan Brandan" },

  { prov: "Sumatera Barat", nama: "Kabupaten Agam" },
  { prov: "Sumatera Barat", nama: "Kabupaten Dharmasraya" },
  { prov: "Sumatera Barat", nama: "Kabupaten Lima Puluh Kota" },
  { prov: "Sumatera Barat", nama: "Kabupaten Padang Pariaman" },
  { prov: "Sumatera Barat", nama: "Kabupaten Pasaman" },
  { prov: "Sumatera Barat", nama: "Kabupaten Pasaman Barat" },
  { prov: "Sumatera Barat", nama: "Kabupaten Pesisir Selatan" },
  { prov: "Sumatera Barat", nama: "Kabupaten Sijunjung" },
  { prov: "Sumatera Barat", nama: "Kabupaten Solok" },
  { prov: "Sumatera Barat", nama: "Kabupaten Solok Selatan" },
  { prov: "Sumatera Barat", nama: "Kabupaten Tanah Datar" },
  { prov: "Sumatera Barat", nama: "Kota Bukittinggi" },
  { prov: "Sumatera Barat", nama: "Kota Padang" },
  { prov: "Sumatera Barat", nama: "Kota Padang Panjang" },
  { prov: "Sumatera Barat", nama: "Kota Pariaman" },
  { prov: "Sumatera Barat", nama: "Kota Payakumbuh" },
  { prov: "Sumatera Barat", nama: "Kota Sawahlunto" },
  { prov: "Sumatera Barat", nama: "Kota Solok" },

  { prov: "Riau", nama: "Kabupaten Bengkalis" },
  { prov: "Riau", nama: "Kabupaten Indragiri Hilir" },
  { prov: "Riau", nama: "Kabupaten Indragiri Hulu" },
  { prov: "Riau", nama: "Kabupaten Kampar" },
  { prov: "Riau", nama: "Kabupaten Kepulauan Meranti" },
  { prov: "Riau", nama: "Kabupaten Kuantan Singingi" },
  { prov: "Riau", nama: "Kabupaten Pelalawan" },
  { prov: "Riau", nama: "Kabupaten Rokan Hilir" },
  { prov: "Riau", nama: "Kabupaten Rokan Hulu" },
  { prov: "Riau", nama: "Kabupaten Siak" },
  { prov: "Riau", nama: "Kota Dumai" },
  { prov: "Riau", nama: "Kota Pekanbaru" },

  { prov: "Kepulauan Riau", nama: "Kabupaten Bintan" },
  { prov: "Kepulauan Riau", nama: "Kabupaten Karimun" },
  { prov: "Kepulauan Riau", nama: "Kabupaten Kepulauan Anambas" },
  { prov: "Kepulauan Riau", nama: "Kabupaten Lingga" },
  { prov: "Kepulauan Riau", nama: "Kabupaten Natuna" },
  { prov: "Kepulauan Riau", nama: "Kota Batam" },
  { prov: "Kepulauan Riau", nama: "Kota Tanjungpinang" },

  { prov: "Jambi", nama: "Kabupaten Batanghari" },
  { prov: "Jambi", nama: "Kabupaten Bungo" },
  { prov: "Jambi", nama: "Kabupaten Kerinci" },
  { prov: "Jambi", nama: "Kabupaten Merangin" },
  { prov: "Jambi", nama: "Kabupaten Muaro Jambi" },
  { prov: "Jambi", nama: "Kabupaten Sarolangun" },
  { prov: "Jambi", nama: "Kabupaten Tanjung Jabung Barat" },
  { prov: "Jambi", nama: "Kabupaten Tanjung Jabung Timur" },
  { prov: "Jambi", nama: "Kabupaten Tebo" },
  { prov: "Jambi", nama: "Kota Jambi" },
  { prov: "Jambi", nama: "Kota Sungai Penuh" },

  { prov: "Bengkulu", nama: "Kabupaten Bengkulu" },
  { prov: "Bengkulu", nama: "Kabupaten Kaur" },
  { prov: "Bengkulu", nama: "Kabupaten Kepahiang" },
  { prov: "Bengkulu", nama: "Kabupaten Lebong" },
  { prov: "Bengkulu", nama: "Kabupaten Mukomuko" },
  { prov: "Bengkulu", nama: "Kabupaten Rejang Lebong" },
  { prov: "Bengkulu", nama: "Kabupaten Seluma" },
  { prov: "Bengkulu", nama: "Kota Bengkulu" },
  { prov: "Bengkulu", nama: "Kota Curup" },

  { prov: "Sumatera Selatan", nama: "Kabupaten Banyuasin" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Empat Lawang" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Lahat" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Muara Enim" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Musi Banyuasin" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Musi Rawas" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Musi Rawas Utara" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Ogan Ilir" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Ogan Komering" },
  { prov: "Sumatera Selatan", nama: "Kabupaten Penukal Abab Lematang Ilir" },
  { prov: "Sumatera Selatan", nama: "Kota Lubuklinggau" },
  { prov: "Sumatera Selatan", nama: "Kota Pagar Alam" },
  { prov: "Sumatera Selatan", nama: "Kota Palembang" },
  { prov: "Sumatera Selatan", nama: "Kota Prabumulih" },
  { prov: "Sumatera Selatan", nama: "Kota Sekayu" },

  { prov: "Bangka Belitung", nama: "Kabupaten Bangka" },
  { prov: "Bangka Belitung", nama: "Kabupaten Bangka Barat" },
  { prov: "Bangka Belitung", nama: "Kabupaten Bangka Selatan" },
  { prov: "Bangka Belitung", nama: "Kabupaten Bangka Tengah" },
  { prov: "Bangka Belitung", nama: "Kabupaten Belitung" },
  { prov: "Bangka Belitung", nama: "Kabupaten Belitung Timur" },
  { prov: "Bangka Belitung", nama: "Kota Pangkal Pinang" },

  { prov: "Lampung", nama: "Kabupaten Lampung Barat" },
  { prov: "Lampung", nama: "Kabupaten Lampung Selatan" },
  { prov: "Lampung", nama: "Kabupaten Lampung Tengah" },
  { prov: "Lampung", nama: "Kabupaten Lampung Timur" },
  { prov: "Lampung", nama: "Kabupaten Lampung Utara" },
  { prov: "Lampung", nama: "Kabupaten Mesuji" },
  { prov: "Lampung", nama: "Kabupaten Pesawaran" },
  { prov: "Lampung", nama: "Kabupaten Pesisir Barat" },
  { prov: "Lampung", nama: "Kabupaten Pringsewu" },
  { prov: "Lampung", nama: "Kabupaten Tanggamus" },
  { prov: "Lampung", nama: "Kabupaten Tulang Bawang" },
  { prov: "Lampung", nama: "Kabupaten Way Kanan" },
  { prov: "Lampung", nama: "Kota Bandar Lampung" },
  { prov: "Lampung", nama: "Kota Metro" },

  { prov: "Banten", nama: "Kabupaten Lebak" },
  { prov: "Banten", nama: "Kabupaten Pandeglang" },
  { prov: "Banten", nama: "Kabupaten Serang" },
  { prov: "Banten", nama: "Kabupaten Tangerang" },
  { prov: "Banten", nama: "Kota Cilegon" },
  { prov: "Banten", nama: "Kota Serang" },
  { prov: "Banten", nama: "Kota Tangerang" },
  { prov: "Banten", nama: "Kota Tangerang Selatan" },

  { prov: "Jawa Barat", nama: "Kabupaten Bandung" },
  { prov: "Jawa Barat", nama: "Kabupaten Bandung Barat" },
  { prov: "Jawa Barat", nama: "Kabupaten Bekasi" },
  { prov: "Jawa Barat", nama: "Kabupaten Bogor" },
  { prov: "Jawa Barat", nama: "Kabupaten Ciamis" },
  { prov: "Jawa Barat", nama: "Kabupaten Cianjur" },
  { prov: "Jawa Barat", nama: "Kabupaten Cirebon" },
  { prov: "Jawa Barat", nama: "Kabupaten Garut" },
  { prov: "Jawa Barat", nama: "Kabupaten Indramayu" },
  { prov: "Jawa Barat", nama: "Kabupaten Karawang" },
  { prov: "Jawa Barat", nama: "Kabupaten Kuningan" },
  { prov: "Jawa Barat", nama: "Kabupaten Majalengka" },
  { prov: "Jawa Barat", nama: "Kabupaten Pangandaran" },
  { prov: "Jawa Barat", nama: "Kabupaten Purwakarta" },
  { prov: "Jawa Barat", nama: "Kabupaten Subang" },
  { prov: "Jawa Barat", nama: "Kabupaten Sukabumi" },
  { prov: "Jawa Barat", nama: "Kabupaten Sumedang" },
  { prov: "Jawa Barat", nama: "Kabupaten Tasikmalaya" },
  { prov: "Jawa Barat", nama: "Kota Bandung" },
  { prov: "Jawa Barat", nama: "Kota Banjar" },
  { prov: "Jawa Barat", nama: "Kota Bekasi" },
  { prov: "Jawa Barat", nama: "Kota Bogor" },
  { prov: "Jawa Barat", nama: "Kota Cimahi" },
  { prov: "Jawa Barat", nama: "Kota Cirebon" },
  { prov: "Jawa Barat", nama: "Kota Depok" },
  { prov: "Jawa Barat", nama: "Kota Sukabumi" },
  { prov: "Jawa Barat", nama: "Kota Tasikmalaya" },
  { prov: "Jawa Barat", nama: "Kota Cikarang" },
  { prov: "Jawa Barat", nama: "Kota Karawang" },
  { prov: "Jawa Barat", nama: "Kota Cikampek" },
  { prov: "Jawa Barat", nama: "Kota Ciamis" },
  { prov: "Jawa Barat", nama: "Kota Cianjur" },
  { prov: "Jawa Barat", nama: "Kota Cirebon" },
  { prov: "Jawa Barat", nama: "Kota Garut" },
  { prov: "Jawa Barat", nama: "Kota Indramayu" },
  { prov: "Jawa Barat", nama: "Kota Kuningan" },
  { prov: "Jawa Barat", nama: "Kota Majalengka" },
  { prov: "Jawa Barat", nama: "Kota Pangandaran" },
  { prov: "Jawa Barat", nama: "Kota Purwakarta" },
  { prov: "Jawa Barat", nama: "Kota Subang" },
  { prov: "Jawa Barat", nama: "Kota Sumedang" },
  { prov: "Jawa Barat", nama: "Kota Tasikmalaya" },

  { prov: "Jawa Tengah", nama: "Kabupaten Banjarnegara" },
  { prov: "Jawa Tengah", nama: "Kabupaten Banyumas" },
  { prov: "Jawa Tengah", nama: "Kabupaten Batang" },
  { prov: "Jawa Tengah", nama: "Kabupaten Blora" },
  { prov: "Jawa Tengah", nama: "Kabupaten Boyolali" },
  { prov: "Jawa Tengah", nama: "Kabupaten Brebes" },
  { prov: "Jawa Tengah", nama: "Kabupaten Cilacap" },
  { prov: "Jawa Tengah", nama: "Kabupaten Demak" },
  { prov: "Jawa Tengah", nama: "Kabupaten Grobogan" },
  { prov: "Jawa Tengah", nama: "Kabupaten Jepara" },
  { prov: "Jawa Tengah", nama: "Kabupaten Karanganyar" },
  { prov: "Jawa Tengah", nama: "Kabupaten Kebumen" },
  { prov: "Jawa Tengah", nama: "Kabupaten Kendal" },
  { prov: "Jawa Tengah", nama: "Kabupaten Klaten" },
  { prov: "Jawa Tengah", nama: "Kabupaten Kudus" },
  { prov: "Jawa Tengah", nama: "Kabupaten Magelang" },
  { prov: "Jawa Tengah", nama: "Kabupaten Pati" },
  { prov: "Jawa Tengah", nama: "Kabupaten Pekalongan" },
  { prov: "Jawa Tengah", nama: "Kabupaten Pemalang" },
  { prov: "Jawa Tengah", nama: "Kabupaten Purbalingga" },
  { prov: "Jawa Tengah", nama: "Kabupaten Purworejo" },
  { prov: "Jawa Tengah", nama: "Kabupaten Rembang" },
  { prov: "Jawa Tengah", nama: "Kabupaten Semarang" },
  { prov: "Jawa Tengah", nama: "Kabupaten Sragen" },
  { prov: "Jawa Tengah", nama: "Kabupaten Sukoharjo" },
  { prov: "Jawa Tengah", nama: "Kabupaten Tegal" },
  { prov: "Jawa Tengah", nama: "Kabupaten Temanggung" },
  { prov: "Jawa Tengah", nama: "Kabupaten Wonogiri" },
  { prov: "Jawa Tengah", nama: "Kabupaten Wonosobo" },
  { prov: "Jawa Tengah", nama: "Kota Magelang" },
  { prov: "Jawa Tengah", nama: "Kota Pekalongan" },
  { prov: "Jawa Tengah", nama: "Kota Salatiga" },
  { prov: "Jawa Tengah", nama: "Kota Semarang" },
  { prov: "Jawa Tengah", nama: "Kota Surakarta" },
  { prov: "Jawa Tengah", nama: "Kota Tegal" },
  { prov: "Jawa Tengah", nama: "Kota Cepu" },
  { prov: "Jawa Tengah", nama: "Kota Banjarnegara" },
  { prov: "Jawa Tengah", nama: "Kota Purwokerto" },
  { prov: "Jawa Tengah", nama: "Kota Batang" },
  { prov: "Jawa Tengah", nama: "Kota Blora" },
  { prov: "Jawa Tengah", nama: "Kota Boyolali" },
  { prov: "Jawa Tengah", nama: "Kota Brebes" },
  { prov: "Jawa Tengah", nama: "Kota Cilacap" },
  { prov: "Jawa Tengah", nama: "Kota Demak" },
  { prov: "Jawa Tengah", nama: "Kota Grobogan" },
  { prov: "Jawa Tengah", nama: "Kota Jepara" },
  { prov: "Jawa Tengah", nama: "Kota Karanganyar" },
  { prov: "Jawa Tengah", nama: "Kota Kebumen" },
  { prov: "Jawa Tengah", nama: "Kota Kendal" },
  { prov: "Jawa Tengah", nama: "Kota Klaten" },
  { prov: "Jawa Tengah", nama: "Kota Kudus" },
  { prov: "Jawa Tengah", nama: "Kota Pati" },
  { prov: "Jawa Tengah", nama: "Kota Pekalongan" },
  { prov: "Jawa Tengah", nama: "Kota Pemalang" },
  { prov: "Jawa Tengah", nama: "Kota Purbalingga" },
  { prov: "Jawa Tengah", nama: "Kota Purworejo" },
  { prov: "Jawa Tengah", nama: "Kota Rembang" },
  { prov: "Jawa Tengah", nama: "Kota Sragen" },
  { prov: "Jawa Tengah", nama: "Kota Temanggung" },
  { prov: "Jawa Tengah", nama: "Kota Wonogiri" },
  { prov: "Jawa Tengah", nama: "Kota Wonosobo" },

  { prov: "DKI Jakarta", nama: "Kota Administrasi Jakarta Barat" },
  { prov: "DKI Jakarta", nama: "Kota Administrasi Jakarta Pusat" },
  { prov: "DKI Jakarta", nama: "Kota Administrasi Jakarta Selatan" },
  { prov: "DKI Jakarta", nama: "Kota Administrasi Jakarta Timur" },
  { prov: "DKI Jakarta", nama: "Kota Administrasi Jakarta Utara" },

  { prov: "D.I. Yogyakarta", nama: "Kabupaten Bantul" },
  { prov: "D.I. Yogyakarta", nama: "Kabupaten Gunungkidul" },
  { prov: "D.I. Yogyakarta", nama: "Kabupaten Kulon Progo" },
  { prov: "D.I. Yogyakarta", nama: "Kabupaten Sleman" },
  { prov: "D.I. Yogyakarta", nama: "Kota Yogyakarta" },

  { prov: "Jawa Timur", nama: "Madura" },
  { prov: "Jawa Timur", nama: "Kabupaten Banyuwangi" },
  { prov: "Jawa Timur", nama: "Kabupaten Blitar" },
  { prov: "Jawa Timur", nama: "Kabupaten Bojonegoro" },
  { prov: "Jawa Timur", nama: "Kabupaten Bondowoso" },
  { prov: "Jawa Timur", nama: "Kabupaten Gresik" },
  { prov: "Jawa Timur", nama: "Kabupaten Jember" },
  { prov: "Jawa Timur", nama: "Kabupaten Jombang" },
  { prov: "Jawa Timur", nama: "Kabupaten Kediri" },
  { prov: "Jawa Timur", nama: "Kabupaten Lamongan" },
  { prov: "Jawa Timur", nama: "Kabupaten Lumajang" },
  { prov: "Jawa Timur", nama: "Kabupaten Madiun" },
  { prov: "Jawa Timur", nama: "Kabupaten Magetan" },
  { prov: "Jawa Timur", nama: "Kabupaten Malang" },
  { prov: "Jawa Timur", nama: "Kabupaten Mojokerto" },
  { prov: "Jawa Timur", nama: "Kabupaten Nganjuk" },
  { prov: "Jawa Timur", nama: "Kabupaten Ngawi" },
  { prov: "Jawa Timur", nama: "Kabupaten Pacitan" },
  { prov: "Jawa Timur", nama: "Kabupaten Pasuruan" },
  { prov: "Jawa Timur", nama: "Kabupaten Ponorogo" },
  { prov: "Jawa Timur", nama: "Kabupaten Probolinggo" },
  { prov: "Jawa Timur", nama: "Kabupaten Sidoarjo" },
  { prov: "Jawa Timur", nama: "Kabupaten Situbondo" },
  { prov: "Jawa Timur", nama: "Kabupaten Sumenep" },
  { prov: "Jawa Timur", nama: "Kabupaten Trenggalek" },
  { prov: "Jawa Timur", nama: "Kabupaten Tuban" },
  { prov: "Jawa Timur", nama: "Kabupaten Tulungagung" },
  { prov: "Jawa Timur", nama: "Kota Batu" },
  { prov: "Jawa Timur", nama: "Kota Blitar" },
  { prov: "Jawa Timur", nama: "Kota Kediri" },
  { prov: "Jawa Timur", nama: "Kota Madiun" },
  { prov: "Jawa Timur", nama: "Kota Malang" },
  { prov: "Jawa Timur", nama: "Kota Mojokerto" },
  { prov: "Jawa Timur", nama: "Kota Pasuruan" },
  { prov: "Jawa Timur", nama: "Kota Probolinggo" },
  { prov: "Jawa Timur", nama: "Kota Surabaya" },
  { prov: "Jawa Timur", nama: "Kota Gresik" },
  { prov: "Jawa Timur", nama: "Kota Bojonegoro" },
  { prov: "Jawa Timur", nama: "Kota Pacitan" },
  { prov: "Jawa Timur", nama: "Kota Tulungagung" },
  { prov: "Jawa Timur", nama: "Kota Mojoagung" },
  { prov: "Jawa Timur", nama: "Kota Ngawi" },
  { prov: "Jawa Timur", nama: "Kota Nganjuk" },
  { prov: "Jawa Timur", nama: "Kota Sidoarjo" },
  { prov: "Jawa Timur", nama: "Kota Lumajang" },
  { prov: "Jawa Timur", nama: "Kota Jombang" },

  { prov: "Bali", nama: "Kabupaten Badung" },
  { prov: "Bali", nama: "Kabupaten Bangli" },
  { prov: "Bali", nama: "Kabupaten Buleleng" },
  { prov: "Bali", nama: "Kabupaten Gianyar" },
  { prov: "Bali", nama: "Kabupaten Jembrana" },
  { prov: "Bali", nama: "Kabupaten Karangasem" },
  { prov: "Bali", nama: "Kabupaten Klungkung" },
  { prov: "Bali", nama: "Kabupaten Tabanan" },
  { prov: "Bali", nama: "Kota Denpasar" },

  { prov: "Nusa Tenggara Barat", nama: "Kabupaten Bima" },
  { prov: "Nusa Tenggara Barat", nama: "Pulau Dompu" },
  { prov: "Nusa Tenggara Barat", nama: "Kabupaten Lombok" },
  { prov: "Nusa Tenggara Barat", nama: "Kabupaten Sumbawa" },
  { prov: "Nusa Tenggara Barat", nama: "Kabupaten Sumbawa Barat" },
  { prov: "Nusa Tenggara Barat", nama: "Kota Bima" },
  { prov: "Nusa Tenggara Barat", nama: "Kota Mataram" },

  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Alor" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Belu" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Ende" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Flores Timur" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Kupang" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Lembata" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Malaka" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Manggarai" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Ngada" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Nagekeo" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Sabu Raijua" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Sikka" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Sumba" },
  { prov: "Nusa Tenggara Timur", nama: "Kabupaten Timor" },
  { prov: "Nusa Tenggara Timur", nama: "Kota Kupang" },

  { prov: "Kalimantan Barat", nama: "Kabupaten Bengkayang" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Kapuas Hulu" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Kayong Utara" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Ketapang" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Kubu Raya" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Landak" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Melawi" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Mempawah" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Sambas" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Sanggau" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Sekadau" },
  { prov: "Kalimantan Barat", nama: "Kabupaten Sintang" },
  { prov: "Kalimantan Barat", nama: "Kota Pontianak" },
  { prov: "Kalimantan Barat", nama: "Kota Singkawang" },

  { prov: "Kalimantan Selatan", nama: "Kabupaten Balangan" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Banjar" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Barito Kuala" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Hulu Sungai Selatan" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Hulu Sungai Tengah" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Hulu Sungai Utara" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Kotabaru" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Tabalong" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Tanah Bumbu" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Tanah Laut" },
  { prov: "Kalimantan Selatan", nama: "Kabupaten Tapin" },
  { prov: "Kalimantan Selatan", nama: "Kota Banjarbaru" },
  { prov: "Kalimantan Selatan", nama: "Kota Banjarmasin" },

  { prov: "Kalimantan Tengah", nama: "Kabupaten Barito Selatan" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Barito Timur" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Barito Utara" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Gunung Mas" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Kapuas" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Katingan" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Kotawaringin Barat" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Kotawaringin Timur" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Lamandau" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Murung Raya" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Pulang Pisau" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Sukamara" },
  { prov: "Kalimantan Tengah", nama: "Kabupaten Seruyan" },
  { prov: "Kalimantan Tengah", nama: "Kota Palangka Raya" },

  { prov: "Kalimantan Timur", nama: "Kabupaten Berau" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Kutai Barat" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Kutai Kartanegara" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Kutai Timur" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Mahakam Ulu" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Paser" },
  { prov: "Kalimantan Timur", nama: "Kabupaten Penajam Paser Utara" },
  { prov: "Kalimantan Timur", nama: "Kota Balikpapan" },
  { prov: "Kalimantan Timur", nama: "Kota Bontang" },
  { prov: "Kalimantan Timur", nama: "Kota Samarinda" },
  { prov: "Kalimantan Timur", nama: "Melak" },

  { prov: "Kalimantan Utara", nama: "Kabupaten Bulungan" },
  { prov: "Kalimantan Utara", nama: "Kabupaten Malinau" },
  { prov: "Kalimantan Utara", nama: "Kabupaten Nunukan" },
  { prov: "Kalimantan Utara", nama: "Kabupaten Tana Tidung" },
  { prov: "Kalimantan Utara", nama: "Kota Tarakan" },

  { prov: "Gorontalo", nama: "Kabupaten Boalemo" },
  { prov: "Gorontalo", nama: "Kabupaten Bone Bolango" },
  { prov: "Gorontalo", nama: "Kabupaten Gorontalo" },
  { prov: "Gorontalo", nama: "Kabupaten Pohuwato" },
  { prov: "Gorontalo", nama: "Kota Gorontalo" },

  { prov: "Sulawesi Selatan", nama: "Kabupaten Bantaeng" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Barru" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Bone" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Bulukumba" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Enrekang" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Gowa" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Jeneponto" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Luwu" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Maros" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Pangkajene dan Kepulauan" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Pinrang" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Sidenreng Rappang" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Sinjai" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Soppeng" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Takalar" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Tana Toraja" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Toraja Utara" },
  { prov: "Sulawesi Selatan", nama: "Kabupaten Wajo" },
  { prov: "Sulawesi Selatan", nama: "Kota Makassar" },
  { prov: "Sulawesi Selatan", nama: "Kota Palopo" },
  { prov: "Sulawesi Selatan", nama: "Kota Parepare" },

  { prov: "Sulawesi Tenggara", nama: "Kabupaten Bombana" },
  { prov: "Sulawesi Tenggara", nama: "Kabupaten Buton" },
  { prov: "Sulawesi Tenggara", nama: "Kabupaten Kolaka" },
  { prov: "Sulawesi Tenggara", nama: "Kabupaten Konawe" },
  { prov: "Sulawesi Tenggara", nama: "Kabupaten Muna" },
  { prov: "Sulawesi Tenggara", nama: "Kabupaten Wakatobi" },
  { prov: "Sulawesi Tenggara", nama: "Kota Bau-Bau" },
  { prov: "Sulawesi Tenggara", nama: "Kota Kendari" },

  { prov: "Sulawesi Tengah", nama: "Kabupaten Banggai" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Buol" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Donggala" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Morowali" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Morowali Utara" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Parigi Moutong" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Poso" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Sigi" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Tojo Una-Una" },
  { prov: "Sulawesi Tengah", nama: "Kabupaten Toli-Toli" },
  { prov: "Sulawesi Tengah", nama: "Bungku Tengah" },
  { prov: "Sulawesi Tengah", nama: "Kolonodale" },
  { prov: "Sulawesi Tengah", nama: "Kota Palu" },

  { prov: "Sulawesi Utara", nama: "Kabupaten Bolaang Mongondow" },
  { prov: "Sulawesi Utara", nama: "Kabupaten Minahasa" },
  { prov: "Sulawesi Utara", nama: "Kota Bitung" },
  { prov: "Sulawesi Utara", nama: "Kota Kotamobagu" },
  { prov: "Sulawesi Utara", nama: "Kota Manado" },
  { prov: "Sulawesi Utara", nama: "Kota Tomohon" },
  { prov: "Sulawesi Utara", nama: "Kota Tondano" },

  { prov: "Sulawesi Barat", nama: "Kabupaten Majene" },
  { prov: "Sulawesi Barat", nama: "Kabupaten Mamasa" },
  { prov: "Sulawesi Barat", nama: "Kabupaten Mamuju" },
  { prov: "Sulawesi Barat", nama: "Kabupaten Polewali Mandar" },
  { prov: "Sulawesi Barat", nama: "Kota Mamuju" },

  { prov: "Maluku", nama: "Kabupaten Seram" },
  { prov: "Maluku", nama: "Kota Ambon" },
  { prov: "Maluku", nama: "Kota Tual" },

  { prov: "Maluku Utara", nama: "Kabupaten Halmahera Barat" },
  { prov: "Maluku Utara", nama: "Kabupaten Halmahera Tengah" },
  { prov: "Maluku Utara", nama: "Kabupaten Halmahera Utara" },
  { prov: "Maluku Utara", nama: "Kabupaten Halmahera Selatan" },
  { prov: "Maluku Utara", nama: "Kabupaten Kepulauan Sula" },
  { prov: "Maluku Utara", nama: "Kabupaten Halmahera Timur" },
  { prov: "Maluku Utara", nama: "Kabupaten Pulau Morotai" },
  { prov: "Maluku Utara", nama: "Kabupaten Pulau Taliabu" },
  { prov: "Maluku Utara", nama: "Kota Ternate" },
  { prov: "Maluku Utara", nama: "Kota Tidore Kepulauan" },
  { prov: "Maluku Utara", nama: "Kota Jailolo" },
  { prov: "Maluku Utara", nama: "Kota Weda" },

  { prov: "Papua", nama: "Kabupaten Jayapura" },
  { prov: "Papua", nama: "Kabupaten Merauke" },
  { prov: "Papua", nama: "Kabupaten Mimika" },
  { prov: "Papua", nama: "Kabupaten Nabire" },
  { prov: "Papua", nama: "Kota Jayapura" },
  { prov: "Papua", nama: "Kota Timika" },

  { prov: "Papua Barat", nama: "Kabupaten Manokwari" },
  { prov: "Papua Barat", nama: "Kabupaten Sorong" },
  { prov: "Papua Barat", nama: "Kabupaten Teluk Bintuni" }
];

console.log("Total raw items in array:", rawData.length);

function getJenis(nama) {
  if (nama.startsWith("Kabupaten ")) return "kabupaten";
  if (nama.startsWith("Kota Administrasi ")) return "kota";
  if (nama.startsWith("Kota ")) return "kota";
  return "lainnya";
}

function makeSlug(nama) {
  let cleaned = nama
    .replace(/^Kabupaten\s+/i, '')
    .replace(/^Kota Administrasi\s+/i, '')
    .replace(/^Kota\s+/i, '')
    .trim();
  return cleaned
    .toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

const slugCounts = {};
const itemMap = [];

rawData.forEach(item => {
  const slug = makeSlug(item.nama);
  const jenis = getJenis(item.nama);
  slugCounts[slug] = (slugCounts[slug] || 0) + 1;
  itemMap.push({
    rawNama: item.nama,
    prov: item.prov,
    jenis: jenis,
    slug: slug
  });
});

const collisions = Object.keys(slugCounts).filter(s => slugCounts[s] > 1);
console.log("Unique slugs count if stripping prefix:", Object.keys(slugCounts).length);
console.log("Colliding slugs count:", collisions.length);
console.log("Collisions detail:");
collisions.forEach(s => {
  const matches = itemMap.filter(i => i.slug === s);
  console.log(`- Slug "${s}":`, matches.map(m => `${m.rawNama} (${m.prov})`).join(" VS "));
});
